[deps]
bottleneck = ""
ipython = ""
netcdf4 = ""
pyproj = ""
matplotlib = ""
pytables = ""
numpydoc = ""
pip = ""
scikit-learn = ""
configobj = ""
libxml2 = ""
seaborn = ""
jupyterlab = ""
libspatialite = ""
rioxarray = ""
pandas = ""
dask = ""
gdal = ""
xarray = ""
jupyter = ""
python = "<3.12"
salem = ""
cartopy = ""
geopandas = ""
typeguard = ""
pytest = ""
shapely = ""
motionless = ""
numpy = "<2.0"
scipy = ""
scikit-image = ""

[pip.deps]
oggm = ""
certifi = ""
progressbar2 = ""
joblib = ""
MBSandbox = "@ git+https://github.com/OGGM/massbalance-sandbox"

[extras]
channels = ["conda-forge"]
