name: Run Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches: []
    tags: '*'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
        python:
          - '3.10'
        os: [ubuntu-latest, macos-latest]
        arch:
          - x64
    steps:
      - name: Cancel ongoing test runs for previous commits
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v4
      - name: Set up Python 🐍 ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install certifi and set SSL_CERT_FILE
        run: |
          pip install --upgrade certifi
          echo "SSL_CERT_FILE=$(python -c 'import certifi; print(certifi.where())')" >> $GITHUB_ENV
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Check Julia SSL certifications 🔎🔐
        run: julia -e 'using NetworkOptions; println(NetworkOptions.bundled_ca_roots()); println(NetworkOptions.ca_roots())'
      - name: Install dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2=2.9.10+dfsg-6.7ubuntu0.1 libxml2-dev=2.9.10+dfsg-6.7ubuntu0.1 libspatialite-dev
          sudo apt-mark hold libxml2 libxml2-dev
          export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
      - name: Rebuild libspatialite
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y build-essential
          wget https://www.gaia-gis.it/gaia-sins/libspatialite-sources/libspatialite-5.0.1.tar.gz
          tar xzf libspatialite-5.0.1.tar.gz
          cd libspatialite-5.0.1
          ./configure
          make
          sudo make install
          sudo ldconfig
      - name: Install dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install libxml2 libspatialite
          export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
      - name: Debug library versions
        if: matrix.os == 'ubuntu-latest'
        run: |
          ldconfig -p | grep libxml
          ldconfig -p | grep libspatialite
          ldd /home/runner/work/Sleipnir.jl/Sleipnir.jl/.CondaPkg/env/lib/libspatialite.so || true
          apt-cache policy libxml2 libspatialite7
      - uses: julia-actions/cache@v2
        with:
          cache-registries: "true"
          cache-compiled: "true"
      - uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Ensure Conda Environment Variables
        run: |
          echo "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/home/runner/work/Sleipnir.jl/Sleipnir.jl/.CondaPkg/env/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/home/runner/work/Sleipnir.jl/Sleipnir.jl/.CondaPkg/env/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
      - uses: julia-actions/julia-buildpkg@v1
        env:
          JULIA_SSL_CA_ROOTS_PATH: ""
      - uses: julia-actions/julia-runtest@latest
        env:
          JULIA_SSL_CA_ROOTS_PATH: ""
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: lcov.info